stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/data_ingestion/lung_colon_ct_scan_image_set


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - artifacts/data_ingestion/lung_colon_ct_scan_image_set
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE_HEAD
      - LEARNING_RATE_FINE
    outs:
      - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/lung_colon_ct_scan_image_set
      - artifacts/prepare_base_model
      - params.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS_HEAD
      - EPOCHS_FINE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/lung_colon_ct_scan_image_set
      - artifacts/training/model.h5
      - params.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false
