artifacts_root : artifacts


data_ingestion :
  root_dir                : artifacts/data_ingestion
  source_URL              : https://drive.google.com/file/d/1eJZYtupcRu7PM4oGjtI_DG4Q31FvtTur/view?usp=sharing  
  local_data_file         : artifacts/data_ingestion/data.zip
  unzip_dir               : artifacts/data_ingestion
  source_dir_name         : chest_ct_scan_images_small


prepare_base_model :
  root_dir                : artifacts/prepare_base_model
  base_model_path         : artifacts/prepare_base_model/base_model.h5
  updated_base_model_path : artifacts/prepare_base_model/base_model_updated.h5
  base_model_type         : vgg16


training :
  root_dir                : artifacts/training
  trained_model_path      : artifacts/training/model.h5
  model_export_path       : model/model.h5

mlflow:
  uri                     : http://ec2-52-66-232-50.ap-south-1.compute.amazonaws.com:5000/
  experiment_name         : "Test on small VGG16 2"
  registered_model_name   : "VGG16_Model_test"
